name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Build with Maven (skip tests)
        run: mvn clean compile -DskipTests
        working-directory: ./backend
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/jobportal_db
          SPRING_DATASOURCE_USERNAME: aashish
          SPRING_DATASOURCE_PASSWORD: aashish123
          SPRING_DATA_REDIS_HOST: localhost
          SPRING_DATA_REDIS_PORT: 6379
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRATION: 86400000
          SPRING_MAIL_USERNAME: dummy@gmail.com
          SPRING_MAIL_PASSWORD: dummypassword